### PR TITLE
feat: Add support for Symantec ICAP

### PR DESCRIPTION
**Pull request by enjeck**
This provides Symantec antivirus support

### CODE REVIEW

**Comment by icewind1991** [comment]
From what I can tell the main difference between this and the existing icap implementation is the handling of the `X-Error-Code` reply header. I'll look into adding that logic to the existing icap scanner instead of duplicating the logic.

**Comment by Philldomd** [comment]
Hi that is correct, all we did was to add error handling from Symantec as it sends 500 codes back. I also added a choice for password protected files as it does mark that as a threat in Symantec, not a virus but still 500 return code. 

I was uncertain about these rows:
https://github.com/nextcloud/files_antivirus/pull/375/commits/a99e80c715c8eb8af3ac4d00a44add867242342e#diff-a33d182d4905d83769450f1fc22983b023638ee35cec5d842f24ae390204a5f4R148-R149

It might be better to dont allow this files than mark them as unchecked.

**Comment by icewind1991** [comment]
I guess the best way forward is to introduce an "unable to scan" result (separate from the "try to rescan later") and let the admin configure to either allow or block those files. That would then also include password protected files.

**Comment by icewind1991** [comment]
wip: https://github.com/nextcloud/files_antivirus/pull/378

**Comment by AndyScherzinger** [comment]
@icewind1991 with #378 merged and afaik tested by the customer-feature-requests, can this PR be closed as bring obsolete? Cc @Philldomd for feedback.

**Comment by icewind1991** [comment]
Yes this can be closed, I'll try to do a release soon

**Pull request closed without merging**
