### PR TITLE
Update runs on, krankler, checkout action and upload artifact action

### PR DESCRIPTION
**Pull request by melroy89**
I updated the package action for you, so it would (in theory) work again.

### CODE REVIEW

**Comment by melroy89** [comment]
> We hope that the review process is going smooth and is helpful for you. We want to ensure your pull request is reviewed to your satisfaction. If you have a moment, our community management team would very much appreciate your feedback on your experience with this PR review process.

Not really.. it's not picked-up yet

**Comment by melroy89** [comment]
There seems to be a syntax error in scanner.yaml?

**Comment by icewind1991** [comment]
That error is caused by secrets not being available from forks

**Comment by melroy89** [comment]
You can disable workflows, jobs and steps using if statements. https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution

**Pull request merged**
