### PR TITLE
Rebase on top of upstream changes

### LINKED ISSUE #13: File not found after Upgrade from Nextcloud 10 to 11
After upgrade from nextcloud 10 to 11 I have issues with files_antivirus.
Admin user log file shows:
`Error	files_antivirus	OCA\Files_Antivirus\BackgroundScanner::run, exception: File with id "7" has not been found.`

I strongly assume this is related to (one) of these?
* https://github.com/owncloud/files_antivirus/issues/98
* https://github.com/owncloud/files_antivirus/pull/118
* https://github.com/owncloud/files_antivirus/pull/127
* https://github.com/owncloud/files_antivirus/pull/128

If I look into the database it seems to be the San Francisco.jpg example file from the installation.
Id 7 let me assume it is the file for the Admin itself.

I have not deleted that file and it still was available.
Afterwards I deleted it, now the database entry shows the file moved to trash `files_trashbin/files/Photos....someid.../San Francisco.jpg`

So something seems to be wrong with the antivirus app itself since the database entry seems to be correct and updated.

### PR DESCRIPTION
**Pull request by icewind1991**
Doing it this way causes less merge conflicts than the other way around so I would prefer to do it this way,

This will mean that github wont be able to merge this PR but we can force push this one to master to apply it.

From the looks of the code it might fix #13 but I have not tested it.

cc @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by icewind1991** [comment]
Tests pass locally, travis doesn't seem to want to run tests on conflicting branches

**Comment by MorrisJobke** [comment]
Let me try to merge this into `run-tests-on-really-old-master` (this is the common commit of this branch and the master branch so travis should be fine merging into this)

**Comment by MorrisJobke** [comment]
Tests pass: https://github.com/nextcloud/files_antivirus/pull/17

**Comment by MorrisJobke** [comment]
> This will mean that github wont be able to merge this PR but we can force push this one to master to apply it.

Okay - I created a backup branch with the current state of master: https://github.com/nextcloud/files_antivirus/tree/old-master

**Comment by MorrisJobke** [comment]
I tested with the clamAV shipped with

> From the looks of the code it might fix #13 but I have not tested it.

I tested with the clamav shipped with Ubuntu 16.04 and it seems to work: 

```
{"reqId":"+P\/GLgRFYUGtQidopk1N","remoteAddr":"10.0.2.2","app":"files_antivirus","message":"Exit code :: 0 Response :: stdin: OK\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 5725070\nEngine version: 0.99.2\nScanned directories: 0\nScanned files: 1\nInfected files: 0\nData scanned: 3.71 MB\nData read: 3.67 MB (ratio 1.01:1)\nTime: 13.130 sec (0 m 13 s)\n","level":0,"time":"2017-02-07T19:09:04+00:00","method":"PUT","url":"\/server\/remote.php\/webdav\/2017-01-14%2005-18-47%202049.jpg","user":"admin","version":"12.0.0.12"}
```

👍

**Comment by MorrisJobke** [comment]
I now got this for the cron-job:

```
{"reqId":"1ZHj8oT2BP9ZUDmQDaxR","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Antivirus\\Cron\\Task job with ID 17","level":0,"time":"2017-02-07T19:14:07+00:00","method":"--","url":"--","user":"--","version":"12.0.0.12"}
{"reqId":"1ZHj8oT2BP9ZUDmQDaxR","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: An exception occurred while executing 'SELECT fc.`fileid, mnt.user_id` FROM `oc_filecache` fc LEFT JOIN `oc_files_antivirus` fa ON fa.`fileid` = fc.`fileid` INNER JOIN `oc_mounts` mnt ON (fc.`storage` = mnt.`storage_id`) AND (mnt.`mount_point` = CONCAT('\/', mnt.user_id, '\/')) WHERE (fc.`mimetype` <> '2') AND ((fa.`fileid` IS NULL) OR (fc.`mtime` > fa.`check_time`)) AND (fc.`path` LIKE 'files\/%') AND (fc.`size` <> '0')':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'fc.fileid, mnt.user_id' in 'field list'","level":3,"time":"2017-02-07T19:14:07+00:00","method":"--","url":"--","user":"--","version":"12.0.0.12"}
{"reqId":"1ZHj8oT2BP9ZUDmQDaxR","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Antivirus\\Cron\\Task job with ID 17","level":0,"time":"2017-02-07T19:14:07+00:00","method":"--","url":"--","user":"--","version":"12.0.0.12"}
```

**Comment by icewind1991** [comment]
@MorrisJobke please retest

**Comment by MorrisJobke** [comment]
> @MorrisJobke please retest

Works now 👍 

I will merge this in the branch and then make this the master branch, okay?

**Comment by MorrisJobke** [comment]
> I will merge this in the branch and then make this the master branch, okay?

Done.

**Comment by MorrisJobke** [comment]
I also tested this with a stable11 instance and it works.

**Pull request merged**
